In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/depri/Desktop/optimisation4th quarter/Project/sales-conversion-optimization/KAG_conversion_data.csv")

In [2]:
indexNames = df[df['xyz_campaign_id'] == 936].index
df.drop(indexNames , inplace=True)

In [3]:
df['cost_per_click']=(df.Spent/df.Clicks)
df['click_through_rate']=1.91
df['clicks_per_conversion']=(df.Clicks/df.Approved_Conversion)
df['cost_per_impression']=(df.Spent/df.Impressions)

In [4]:
df

,ad_id,xyz_campaign_id,fb_campaign_id,age,gender,interest,Impressions,Clicks,Spent,Total_Conversion,Approved_Conversion,cost_per_click,click_through_rate,clicks_per_conversion,cost_per_impression
0,708746,916,103916,30-34,M,15,7350,1,1.430000,2,1,1.430000,1.91,1.000000,0.000195
1,708749,916,103917,30-34,M,16,17861,2,1.820000,2,0,0.910000,1.91,inf,0.000102
2,708771,916,103920,30-34,M,20,693,0,0.000000,1,0,NaN,1.91,NaN,0.000000
3,708815,916,103928,30-34,M,28,4259,1,1.250000,1,0,1.250000,1.91,inf,0.000293
4,708818,916,103928,30-34,M,28,4133,1,1.290000,1,1,1.290000,1.91,1.000000,0.000312
5,708820,916,103929,30-34,M,29,1915,0,0.000000,1,1,NaN,1.91,0.000000,0.000000
6,708889,916,103940,30-34,M,15,15615,3,4.770000,1,0,1.590000,1.91,inf,0.000305
7,708895,916,103941,30-34,M,16,10951,1,1.270000,1,1,1.270000,1.91,1.000000,0.000116
8,708953,916,103951,30-34,M,27,2355,1,1.500000,1,0,1.500000,1.91,inf,0.000637
9,708958,916,103952,30-34,M,28,9502,3,3.160000,1,0,1.053333,1.91,inf,0.000333
10,708979,916,103955,30-34,M,31,1224,0,0.000000,1,0,NaN,1.91,NaN,0.000000
11,709023,916,103962,30-34,M,7,735,0,0.000000,1,0,NaN,1.91,NaN,0.000000
12,709038,916,103965,30-34,M,16,5117,0,0.000000,1,0,NaN,1.91,NaN,0.000000
13,709040,916,103965,30-34,M,16,5120,0,0.000000,1,0,NaN,1.91,NaN,0.000000
14,709059,916,103968,30-34,M,20,14669,7,10.280000,1,1,1.468571,1.91,7.000000,0.000701
15,709105,916,103976,30-34,M,28,1241,0,0.000000,1,1,NaN,1.91,0.000000,0.000000
16,709115,916,103978,30-34,M,30,2305,1,0.570000,1,0,0.570000,1.91,inf,0.000247
17,709124,916,103979,30-34,M,31,1024,0,0.000000,1,1,NaN,1.91,0.000000,0.000000
18,709179,916,103988,35-39,M,15,4627,1,1.690000,1,0,1.690000,1.91,inf,0.000365
19,709183,916,103989,35-39,M,16,21026,4,4.630000,2,1,1.157500,1.91,4.000000,0.000220
20,709320,916,104012,35-39,M,15,1422,0,0.000000,1,1,NaN,1.91,0.000000,0.000000
21,709323,916,104012,35-39,M,15,7132,2,2.610000,1,0,1.305000,1.91,inf,0.000366
22,709326,916,104013,35-39,M,16,12190,2,3.050000,1,0,1.525000,1.91,inf,0.000250
23,709327,916,104013,35-39,M,16,12193,2,3.060000,1,1,1.530000,1.91,2.000000,0.000251
24,709328,916,104013,35-39,M,16,3332,0,0.000000,1,1,NaN,1.91,0.000000,0.000000
25,709455,916,104034,35-39,M,7,559,0,0.000000,1,0,NaN,1.91,NaN,0.000000
26,709544,916,104049,35-39,M,29,7440,2,2.980000,1,1,1.490000,1.91,2.000000,0.000401
27,709614,916,104061,40-44,M,16,19113,4,5.520000,1,0,1.380000,1.91,inf,0.000289
28,709756,916,104085,40-44,M,16,10976,2,1.690000,1,1,0.845000,1.91,2.000000,0.000154
29,709761,916,104085,40-44,M,16,2861,0,0.000000,1,0,NaN,1.91,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113,1314384,1178,179951,35-39,F,113,441192,53,77.600000,6,2,1.464151,1.91,26.500000,0.000176
1114,1314385,1178,179952,35-39,F,114,90470,11,16.730000,1,1,1.520909,1.91,11.000000,0.000185
1115,1314386,1178,179953,40-44,F,100,834243,166,246.749998,18,7,1.486446,1.91,23.714286,0.000296
1116,1314387,1178,179954,40-44,F,101,696612,152,223.189995,31,9,1.468355,1.91,16.888889,0.000320
1117,1314388,1178,179955,40-44,F,102,329333,48,67.609999,1,0,1.408542,1.91,inf,0.000205
1118,1314389,1178,179956,40-44,F,103,1114711,224,319.000002,6,0,1.424107,1.91,inf,0.000286
1119,1314390,1178,179957,40-44,F,104,267316,58,82.929999,3,0,1.429828,1.91,inf,0.000310
1120,1314391,1178,179958,40-44,F,105,228629,38,57.000000,2,0,1.500000,1.91,inf,0.000249
1121,1314392,1178,179959,40-44,F,106,758340,159,233.110002,13,4,1.466101,1.91,39.750000,0.000307
1122,1314393,1178,179960,40-44,F,107,877535,149,217.779997,5,2,1.461611,1.91,74.500000,0.000248
1123,1314394,1178,179961,40-44,F,108,1357386,223,323.060007,10,1,1.448700,1.91,223.000000,0.000238
1124,1314395,1178,179962,40-44,F,109,280240,61,87.990002,2,2,1.442459,1.91,30.500000,0.000314
1125,1314396,1178,179963,40-44,F,110,419922,75,105.450001,3,1,1.406000,1.91,75.000000,0.000251
1126,1314397,1178,179964,40-44,F,111,402975,83,120.899998,1,0,1.456626,1.91,inf,0.000300
1127,1314398,1178,179965,40-44,F,112,1137635,211,301.049999,30,10,1.426777,1.91,21.100000,0.000265
1128,1314400,1178,179967,40-44,F,114,250234,40,62.319999,4,1,1.558000,1.91,40.000000,0.000249
1129,1314401,1178,179968,45-49,F,100,904907,195,279.219995,11,1,1.431897,1.91,195.000000,0.000309
1130,1314402,1178,179969,45-49,F,101,589270,107,158.050002,10,4,1.477103,1.91,26.750000,0.000268
1131,1314403,1178,179970,45-49,F,102,168714,24,36.010001,2,2,1.500417,1.91,12.000000,0.000213
1132,1314404,1178,179971,45-49,F,103,71982,11,16.340001,1,0,1.485455,1.91,inf,0.000227
1133,1314405,1178,179972,45-49,F,104,558666,110,162.639998,14,5,1.478545,1.91,22.000000,0.000291
1134,1314406,1178,179973,45-49,F,105,1118200,235,333.749994,11,4,1.420213,1.91,58.750000,0.000298
1135,1314407,1178,179974,45-49,F,106,107100,23,33.710001,1,0,1.465652,1.91,inf,0.000315
1136,1314408,1178,179975,45-49,F,107,877769,160,232.590001,13,4,1.453688,1.91,40.000000,0.000265
1137,1314409,1178,179976,45-49,F,108,212508,33,47.690000,4,1,1.445152,1.91,33.000000,0.000224
1138,1314410,1178,179977,45-49,F,109,1129773,252,358.189997,13,2,1.421389,1.91,126.000000,0.000317
1139,1314411,1178,179978,45-49,F,110,637549,120,173.880003,3,0,1.449000,1.91,inf,0.000273
1140,1314412,1178,179979,45-49,F,111,151531,28,40.289999,2,0,1.438929,1.91,inf,0.000266
1141,1314414,1178,179981,45-49,F,113,790253,135,198.710000,8,2,1.471926,1.91,67.500000,0.000251
1142,1314415,1178,179982,45-49,F,114,513161,114,165.609999,5,2,1.452719,1.91,57.000000,0.000323

In [5]:
df1=df[['gender','cost_per_click','clicks_per_conversion','click_through_rate','cost_per_impression']]

In [6]:
df1

,gender,cost_per_click,clicks_per_conversion,click_through_rate,cost_per_impression
0,M,1.430000,1.000000,1.91,0.000195
1,M,0.910000,inf,1.91,0.000102
2,M,NaN,NaN,1.91,0.000000
3,M,1.250000,inf,1.91,0.000293
4,M,1.290000,1.000000,1.91,0.000312
5,M,NaN,0.000000,1.91,0.000000
6,M,1.590000,inf,1.91,0.000305
7,M,1.270000,1.000000,1.91,0.000116
8,M,1.500000,inf,1.91,0.000637
9,M,1.053333,inf,1.91,0.000333
10,M,NaN,NaN,1.91,0.000000
11,M,NaN,NaN,1.91,0.000000
12,M,NaN,NaN,1.91,0.000000
13,M,NaN,NaN,1.91,0.000000
14,M,1.468571,7.000000,1.91,0.000701
15,M,NaN,0.000000,1.91,0.000000
16,M,0.570000,inf,1.91,0.000247
17,M,NaN,0.000000,1.91,0.000000
18,M,1.690000,inf,1.91,0.000365
19,M,1.157500,4.000000,1.91,0.000220
20,M,NaN,0.000000,1.91,0.000000
21,M,1.305000,inf,1.91,0.000366
22,M,1.525000,inf,1.91,0.000250
23,M,1.530000,2.000000,1.91,0.000251
24,M,NaN,0.000000,1.91,0.000000
25,M,NaN,NaN,1.91,0.000000
26,M,1.490000,2.000000,1.91,0.000401
27,M,1.380000,inf,1.91,0.000289
28,M,0.845000,2.000000,1.91,0.000154
29,M,NaN,NaN,1.91,0.000000
...,...,...,...,...,...
1113,F,1.464151,26.500000,1.91,0.000176
1114,F,1.520909,11.000000,1.91,0.000185
1115,F,1.486446,23.714286,1.91,0.000296
1116,F,1.468355,16.888889,1.91,0.000320
1117,F,1.408542,inf,1.91,0.000205
1118,F,1.424107,inf,1.91,0.000286
1119,F,1.429828,inf,1.91,0.000310
1120,F,1.500000,inf,1.91,0.000249
1121,F,1.466101,39.750000,1.91,0.000307
1122,F,1.461611,74.500000,1.91,0.000248
1123,F,1.448700,223.000000,1.91,0.000238
1124,F,1.442459,30.500000,1.91,0.000314
1125,F,1.406000,75.000000,1.91,0.000251
1126,F,1.456626,inf,1.91,0.000300
1127,F,1.426777,21.100000,1.91,0.000265
1128,F,1.558000,40.000000,1.91,0.000249
1129,F,1.431897,195.000000,1.91,0.000309
1130,F,1.477103,26.750000,1.91,0.000268
1131,F,1.500417,12.000000,1.91,0.000213
1132,F,1.485455,inf,1.91,0.000227
1133,F,1.478545,22.000000,1.91,0.000291
1134,F,1.420213,58.750000,1.91,0.000298
1135,F,1.465652,inf,1.91,0.000315
1136,F,1.453688,40.000000,1.91,0.000265
1137,F,1.445152,33.000000,1.91,0.000224
1138,F,1.421389,126.000000,1.91,0.000317
1139,F,1.449000,inf,1.91,0.000273
1140,F,1.438929,inf,1.91,0.000266
1141,F,1.471926,67.500000,1.91,0.000251
1142,F,1.452719,57.000000,1.91,0.000323

In [7]:
df1=df1.replace([np.inf, -np.inf], np.nan)

In [8]:
df1.groupby(['gender']).mean()

,cost_per_click,clicks_per_conversion,click_through_rate,cost_per_impression
gender,,,,
F,1.458673,48.582710,1.91,0.000287
M,1.638510,25.755653,1.91,0.000222

In [9]:
"""XYZ Clothing is introducing a new line. The marketing department is going to invest social spending into facebook ads
for two groups: 1) Men and 2) women. The cost per click on the previous ad campaign was $1.46 for women and $1.64 for men.
For every 49 clicks 1 woman converts versus 1 man for every 26 clicks. We having the following goals:
1. get 400 conversions from women
2. get 500 conversions from men
3. Limit the expense of marketing to 100,000
Assume goals are all equally important
"""

'XYZ Clothing is introducing a new line. The marketing department is going to invest social spending into facebook ads\nfor two groups: 1) Men and 2) women. The cost per click on the previous ad campaign was $1.46 for women and $1.64 for men.\nFor every 49 clicks 1 woman converts versus 1 man for every 26 clicks. We having the following goals:\n1. get 400 conversions from women\n2. get 500 conversions from men\n3. Limit the expense of marketing to 100,000\nAssume goals are all equally important\n'

In [10]:
from pulp import *
model = pulp.LpProblem("under/overachievement minimizing problem", pulp.LpMinimize)
x1 = pulp.LpVariable("x1", lowBound=0, cat='Integer') #number of women who see
y1 = pulp.LpVariable("y1", lowBound=0, cat='Integer') #number of men who see
x2 = pulp.LpVariable('x2', lowBound=0, cat='Continuous')#cost
d1_plus = pulp.LpVariable('d1_plus', lowBound=0, cat='Integer')#over rep group one
d1_neg = pulp.LpVariable("d1_neg", lowBound=0, cat='Integer') #under represent group one
d2_plus = pulp.LpVariable('d2_plus', lowBound=0, cat='Integer')#ober rep group 2
d2_neg = pulp.LpVariable('d2_neg', lowBound=0, cat='Integer')#under represent group 2
d3_plus = pulp.LpVariable('d3_plus', lowBound=0, cat='Continuous')#over expense
d3_neg = pulp.LpVariable('d3_neg', lowBound=0, cat='Continuous')#under expense


# Objective function
model += d1_neg + d2_neg + d3_plus, "under_over"


# Constraints
model += x1 + d1_neg - d1_plus == 3711512 #number of women to see to get 300 women to convert
model += y1 + d2_neg - d2_plus == 2460080 #number men to see to get 300 men to convert
model += x1*0.0029 + y1*0.0022 - d3_plus + d3_neg == 18000

model.solve()
LpStatus[model.status]

print('number of group one individuals contacted ={}'.format(x1.varValue))
print('number of group two individuals contacted = {}'.format(y1.varValue))
print('Overachievement of letters sent to group 1 ={}'.format(d1_plus.varValue))
print('Overachievement of letters sent to group 2 = {}'.format(d2_plus.varValue))
print('Over budget = {}'.format(d3_plus.varValue))
print('Under budget = {}'.format(d3_neg.varValue))

number of group one individuals contacted =3711512.0
number of group two individuals contacted = 2460080.0
Overachievement of letters sent to group 1 =0.0
Overachievement of letters sent to group 2 = 0.0
Over budget = 0.0
Under budget = 1824.4392